version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: virtualstack
      POSTGRES_PASSWORD: virtualstack
      POSTGRES_DB: virtualstack
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U virtualstack"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A virtualstack.workers.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://virtualstack:virtualstack@postgres:5432/virtualstack
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  db_test:
    image: postgres:15
    container_name: virtualstack_db_test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: virtualstack_test
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  redis_data:
  postgres_test_data:
    driver: local 