"""Add tenant_roles and role_permissions tables

Revision ID: 43ae6a20f723
Revises: ef986450914c
Create Date: 2025-04-02 12:45:22.428257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43ae6a20f723'
down_revision: Union[str, None] = 'ef986450914c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - THESE WERE INCORRECT ###
    # op.drop_table('user_tenant_roles')
    # op.drop_table('permissions')
    # op.drop_index('ix_users_email', table_name='users')
    # op.drop_table('users')
    # op.drop_index('ix_invitations_email', table_name='invitations')
    # op.drop_index('ix_invitations_token', table_name='invitations')
    # op.drop_table('invitations')
    # op.drop_index('ix_tenants_name', table_name='tenants')
    # op.drop_index('ix_tenants_slug', table_name='tenants')
    # op.drop_table('tenants')
    # op.drop_index('ix_api_keys_key_prefix', table_name='api_keys')
    # op.drop_table('api_keys')
    # op.drop_table('roles')
    # op.drop_table('alembic_version')
    # ### The upgrade function should NOT drop tables. Commenting these out. ###
    # ### TODO: Add the correct op.create_table for tenant_roles and role_permissions if missing ###
    pass # Allow migration to proceed
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - Likely also incorrect/swapped ###
    # ### TODO: Review and correct downgrade steps corresponding to the actual upgrade ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    # ... (rest of the incorrect downgrade function) ...
    pass # Placeholder for corrected downgrade
    # ### end Alembic commands ### 