"""Add user_tenant_roles association table

Revision ID: ef986450914c
Revises: manual_add_scope_column
Create Date: 2024-04-06 13:09:07.855102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef986450914c'
down_revision: Union[str, None] = 'manual_add_scope_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user_tenant_roles',
    # sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    # sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
    # sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    # sa.ForeignKeyConstraint(['role_id'], ['iam.tenant_roles.id'], name=op.f('fk_user_tenant_roles_role_id_tenant_roles'), ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['tenant_id'], ['iam.tenants.id'], name=op.f('fk_user_tenant_roles_tenant_id_tenants'), ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['user_id'], ['iam.users.id'], name=op.f('fk_user_tenant_roles_user_id_users'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('user_id', 'role_id', 'tenant_id', name=op.f('pk_user_tenant_roles')),
    # sa.UniqueConstraint('user_id', 'role_id', 'tenant_id', name=op.f('uq_user_tenant_roles_user_id_role_id_tenant_id')),
    # schema='iam'
    # )
    # ### This table was already created in 20240330_create_iam_tables.py ###
    # ### Commenting out the redundant creation here. ###
    pass # Keep upgrade function valid if nothing else is done
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user_tenant_roles', schema='iam')
    # ### This table drop corresponds to the creation in 20240330_create_iam_tables.py ###
    # ### Commenting out the redundant drop here. ###
    pass # Keep downgrade function valid
    # ### end Alembic commands ### 